package edge

import (
	"fmt"
	"strings"
)

type leafConfParams struct {
	OperatorJWT   string
	AccountPub    string
	AccountJWT    string
	SysAccountPub string
	SysAccountJWT string
	Domain        string
	HubLeafURL    string
	CredsName     string
}

func buildLeafConf(p leafConfParams) string {
	var b strings.Builder
	b.WriteString("# Generated by `agent -leaf-config`. Do not edit by hand.\n")
	b.WriteString("# Regenerate with `agent -leaf-config` if the account JWT rotates.\n\n")
	fmt.Fprintf(&b, "server_name: %q\n\n", p.Domain)
	fmt.Fprintf(&b, "jetstream {\n  domain: %q\n  store_dir: \"./jetstream\"\n}\n\n", p.Domain)
	fmt.Fprintf(&b, "operator: %q\n\n", p.OperatorJWT)
	b.WriteString("resolver: MEMORY\n")

	// Two entries, both mandatory.
	//
	// The org account is what this edge actually uses. The system account is
	// named inside the operator JWT, and nats-server resolves it while
	// constructing the server — with resolver: MEMORY there is nowhere else to
	// fetch it from, so preloading only the org account fails outright with
	// "error resolving system account: account missing", before JetStream is
	// even reached. pb-nats preloads it into the hub's config for the same
	// reason (see its generateOperatorConf).
	//
	// This preloads the system account's JWT, which is public trust material
	// like the operator and org account JWTs already here. It does NOT give the
	// edge a $SYS identity: connecting as the system account needs a $SYS *user*
	// credential, which is never served to a leaf node. "No local $SYS" still
	// holds — monitoring is the localhost HTTP port below, not a $SYS user.
	b.WriteString("resolver_preload: {\n")
	fmt.Fprintf(&b, "  %s: %q\n", p.AccountPub, p.AccountJWT)
	fmt.Fprintf(&b, "  %s: %q\n", p.SysAccountPub, p.SysAccountJWT)
	b.WriteString("}\n\n")

	// `account` is required on every remote in operator mode — nats-server
	// rejects the config without it ("operator mode requires account nkeys in
	// remotes"). It names which local account the leaf connection binds to,
	// which for a one-account edge is the org account.
	fmt.Fprintf(&b, "leafnodes {\n  remotes: [\n    { url: %q, account: %q, credentials: %q }\n  ]\n}\n\n",
		p.HubLeafURL, p.AccountPub, p.CredsName)

	b.WriteString("# Local monitoring only (no $SYS user); keep bound to localhost.\n")
	b.WriteString("http: \"127.0.0.1:8222\"\n")
	return b.String()
}
